events {
    worker_connections 1024;
}

http {
    # Chia tải luồng API (Backend)
    upstream api_servers {
        server api1:3000;
        server api2:3000;
        server api3:3000;
    }

    # Trỏ luồng Web (Frontend)
    upstream web_server {
        server web:80;
    }

    server {
        listen 80;
        server_name unihub.tech www.unihub.tech localhost _; # Thêm localhost để curl test được

        # Mọi request bắt đầu bằng /api sẽ được đẩy vào cụm Node.js
        location /api/ {
            proxy_pass http://api_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Mọi request khác sẽ trả về giao diện ReactJS
        location / {
            proxy_pass http://web_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}