name: Frontend (Web) CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'source/web/**'
      - 'source/.docker/web.Dockerfile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'source/web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source/web
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Web Code
        run: npm run build
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Web Image
        uses: docker/build-push-action@v5
        with:
          context: ./source
          file: ./source/.docker/web.Dockerfile
          push: false # Đổi thành true để push lên DockerHub/GHCR
          tags: unihub-web:latest
